// API (APLICATION PROGRAMMIN INTERFACE)
// EN JS EXISTE UNA FUNCION LA CUAL SE ENCARAG DE HACER LA PETICION DE ESA DATA 

//FECTH()
// DIFERENTES TIPOS DE PETICIONES 
//GET = SIRVE PARA OBTENER INFO 
// POST = SIVE PARA CREAR DATOS 
// PUT = SIRVE PARA ACTUALIZAR DATOS 
// DELETE 

// FUNCION ASYNC 
// FUNCIONES FUERON CREAD PARA EL CONSUMOS DE SERVICIOS 

// 